# Configuration Cloud Build pour Google Cloud Run
# Utilise Artifact Registry (europe-west1-docker.pkg.dev) au lieu de gcr.io

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:latest', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'crm-api'
    - '--image'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:latest'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '300'
    - '--concurrency'
    - '80'
    - '--add-cloudsql-instances'
    - 'thiernew:europe-west1:crm-postgres-prod'
    - '--set-env-vars'
    - 'NODE_ENV=production,PGHOST=/cloudsql/thiernew:europe-west1:crm-postgres-prod,PGDATABASE=2thier,PGUSER=postgres,FRONTEND_URL=https://app.2thier.be,BACKEND_URL=https://app.2thier.be'
    - '--update-secrets'
    - 'PGPASSWORD=crm-postgres-password:latest,JWT_SECRET=JWT_SECRET:latest,SESSION_SECRET=SESSION_SECRET:latest,ENCRYPTION_KEY=ENCRYPTION_KEY:latest,CRYPTO_SECRET_KEY=CRYPTO_SECRET_KEY:latest,GOOGLE_AI_API_KEY=GOOGLE_AI_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest'

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY