# Configuration Cloud Build pour Google Cloud Run
# Utilise Artifact Registry (europe-west1-docker.pkg.dev) au lieu de gcr.io
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'crm-api'
    - '--image'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '300'
    - '--concurrency'
    - '80'
    - '--add-cloudsql-instances'
    - 'thiernew:europe-west1:crm-postgres-prod'
    - '--set-env-vars'
    - 'NODE_ENV=production,PORT=8080,PGHOST=/cloudsql/thiernew:europe-west1:crm-postgres-prod,PGDATABASE=2thier,PGUSER=postgres,FRONTEND_URL=https://app.2thier.be,BACKEND_URL=https://app.2thier.be'
    - '--update-secrets'
    - 'PGPASSWORD=crm-postgres-password:latest,JWT_SECRET=crm-jwt-secret:latest,SESSION_SECRET=crm-session-secret:latest,ENCRYPTION_KEY=crm-encryption-key:latest,CRYPTO_SECRET_KEY=crm-crypto-secret:latest,GOOGLE_AI_API_KEY=google-ai-api-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest'

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA'