# Configuration Cloud Build pour Google Cloud Run
# Utilise Artifact Registry (europe-west1-docker.pkg.dev) au lieu de gcr.io
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'crm-api'
    - '--image'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '4000'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'NODE_ENV=production'

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/crm-2thier/app:$COMMIT_SHA'