-- Script pour vider TOUTES les tables
TRUNCATE TABLE "_prisma_migrations" CASCADE;
TRUNCATE TABLE "User" CASCADE;
TRUNCATE TABLE "Organization" CASCADE;
TRUNCATE TABLE "Role" CASCADE;
TRUNCATE TABLE "Permission" CASCADE;
TRUNCATE TABLE "Module" CASCADE;
TRUNCATE TABLE "Category" CASCADE;
TRUNCATE TABLE "Lead" CASCADE;
TRUNCATE TABLE "Block" CASCADE;
TRUNCATE TABLE "TreeBranchLeafTree" CASCADE;
TRUNCATE TABLE "TreeBranchLeafNode" CASCADE;
TRUNCATE TABLE "TreeBranchLeafSubmission" CASCADE;
TRUNCATE TABLE "WebSite" CASCADE;
TRUNCATE TABLE "website_sections" CASCADE;
TRUNCATE TABLE "PublicForm" CASCADE;
