services:
  crm:
    image: ${GHCR_IMAGE:-ghcr.io/dethierjonathan/2thier/crm:latest}
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    ports:
      - "${APP_PORT:-4000}:4000"
