export type RawTreeNode = {
  id: string;
  parentId: string | null;
  type: string;
  label: string;
  order: number;
  sharedReferenceIds?: string[];
  sharedReferenceName?: string;
  sharedReferenceDescription?: string;
  fieldType?: string;
  subType?: string;
  field_label?: string | null;
  option_label?: string | null;
  value?: string | null;
  isRequired?: boolean;
  isVisible?: boolean;
  description?: string | null;
  text_placeholder?: string | null;
  text_minLength?: number | null;
  text_maxLength?: number | null;
  text_rows?: number | null;
  text_mask?: string | null;
  text_regex?: string | null;
  text_defaultValue?: string | null;
  number_min?: number | null;
  number_max?: number | null;
  number_step?: number | null;
  number_decimals?: number | null;
  number_prefix?: string | null;
  number_suffix?: string | null;
  number_unit?: string | null;
  number_defaultValue?: number | null;
  date_format?: string | null;
  date_showTime?: boolean | null;
  date_defaultValue?: string | null;
  date_minDate?: string | null;
  date_maxDate?: string | null;
  select_multiple?: boolean | null;
  select_searchable?: boolean | null;
  select_allowClear?: boolean | null;
  select_defaultValue?: string | null;
  bool_trueLabel?: string | null;
  bool_falseLabel?: string | null;
  bool_defaultValue?: boolean | null;
  appearance_size?: string | null;
  appearance_width?: string | null;
  appearance_variant?: string | null;
  data_instances?: Record<string, unknown> | null;
  data_activeId?: string | null;
  formula_instances?: Record<string, unknown> | null;
  formula_activeId?: string | null;
  condition_instances?: Record<string, unknown> | null;
  condition_activeId?: string | null;
  table_instances?: Record<string, unknown> | null;
  table_activeId?: string | null;
  api_instances?: Record<string, unknown> | null;
  api_activeId?: string | null;
  link_instances?: Record<string, unknown> | null;
  link_activeId?: string | null;
  markers_instances?: Record<string, unknown> | null;
  markers_activeId?: string | null;
  metadata?: Record<string, unknown> | null;
  name?: string | null;
  [key: string]: unknown;
};
