name: DB Backup
on:
  schedule:
    - cron: '0 2 * * *' # Tous les jours à 02:00 UTC
  workflow_dispatch: {}
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Create backup file
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then echo "DATABASE_URL secret manquant" && exit 1; fi
          TS=$(date +"%Y%m%d_%H%M%S")
          F="db_backup_$TS.sql"
          pg_dump --no-owner --no-privileges "$DATABASE_URL" > "$F"
          echo "BACKUP_FILE=$F" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BACKUP_FILE }}
          path: ${{ env.BACKUP_FILE }}
          retention-days: 14
